
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'coaching_rules_slug_key') THEN
    ALTER TABLE public.coaching_rules ADD CONSTRAINT coaching_rules_slug_key UNIQUE (slug);
  END IF;
END $$;

INSERT INTO public.exercises (slug, title, description, target_metric, target_delta, difficulty) VALUES
  ('bass-swap-4beat',     '4-Beat Bass Swap',        'At every 16-bar boundary cut Deck A bass exactly as you bring Deck B bass up. Record 5 attempts and re-upload.', 'bassStability', 15, 2),
  ('beatmatch-by-ear',    'Beatmatch by Ear (90s)',  'Set both decks to the same BPM with sync OFF and beatmatch by ear for 90 seconds without drifting more than 1 beat.', 'bpmConfidence', 0.15, 2),
  ('harmonic-camelot-1',  'Camelot ±1 Drill',        'Mix three tracks staying within ±1 step on the Camelot wheel. Note the keys before you start.', 'keyConfidence', 0.2, 2),
  ('phrase-16bar',        '16-Bar Phrase Challenge', 'Align two tracks so every transition lands on a 16-bar phrase boundary. No early cuts.', 'flow', 10, 2),
  ('eq-thirds',           'Even-Thirds EQ',          'During the next transition keep bass, mid and high energy roughly even — no band should dominate for more than 4 beats.', 'bandBalance', 10, 1),
  ('headroom-6db',        'Leave 6 dB Headroom',     'Reduce master output until peaks sit around -6 dBFS, then re-record the same mix.', 'loudnessDbfs', -6, 1),
  ('dynamic-build',       'Dynamic Build-Up',        'Construct a 32-bar build where energy climbs by at least 30/100 between start and drop.', 'dynamicRangeDb', 4, 2),
  ('filter-only',         'Filter-Only Transition',  'Transition between two tracks using only a high-pass filter sweep — no EQ swaps, no effects.', 'creativity', 10, 1),
  ('long-blend-32',       '32-Bar Long Blend',       'Layer two tracks for a full 32-bar blend, no cut, no echo-out. Keep basslines from clashing.', 'flow', 8, 3),
  ('echo-tail-out',       'Echo-Tail Transition',    'End the outgoing track with an echo tail at the phrase boundary while the incoming track takes over.', 'creativity', 10, 2)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  target_metric = EXCLUDED.target_metric,
  target_delta = EXCLUDED.target_delta,
  difficulty = EXCLUDED.difficulty;

INSERT INTO public.coaching_rules (slug, title, condition, diagnosis, fix, severity, exercise_id) VALUES
  ('bass-unstable-severe', 'Bass energy is unstable',
   '{"all":[{"metric":"bassStability","op":"<","value":55}]}'::jsonb,
   'Bass energy fluctuates a lot — two basslines are likely fighting during the transition.',
   'Stagger your low-EQ cuts so that no more than one bassline plays at full volume at any time. Always cut the outgoing bass BEFORE bringing the incoming bass up.',
   'critical',
   (SELECT id FROM public.exercises WHERE slug = 'bass-swap-4beat')),
  ('bass-unstable-mild', 'Bass not fully locked',
   '{"all":[{"metric":"bassStability","op":"<","value":75},{"metric":"bassStability","op":">=","value":55}]}'::jsonb,
   'Bass energy varies noticeably across the track.',
   'Practice clean low-EQ swaps at every 16-bar boundary.',
   'warning',
   (SELECT id FROM public.exercises WHERE slug = 'bass-swap-4beat')),
  ('bpm-drift-severe', 'Tempo drifts heavily',
   '{"all":[{"metric":"bpmConfidence","op":"<","value":0.6}]}'::jsonb,
   'The first and second half of the track disagree strongly on the tempo — sync is likely drifting or the mix changes BPM.',
   'Re-check sync before every phrase. If you''re mixing by ear, beatmatch slowly and ride the pitch fader.',
   'critical',
   (SELECT id FROM public.exercises WHERE slug = 'beatmatch-by-ear')),
  ('bpm-drift-mild', 'Tempo slightly unstable',
   '{"all":[{"metric":"bpmConfidence","op":"<","value":0.8},{"metric":"bpmConfidence","op":">=","value":0.6}]}'::jsonb,
   'Tempo agreement between halves is below 80%.',
   'Tighten the beat grid on both tracks before the transition.',
   'warning',
   (SELECT id FROM public.exercises WHERE slug = 'beatmatch-by-ear')),
  ('key-ambiguous', 'Key is ambiguous',
   '{"all":[{"metric":"keyConfidence","op":"<","value":0.35}]}'::jsonb,
   'Key detection confidence is low — the mix likely modulates or sits between keys.',
   'Double-check the keys of both tracks manually before harmonic mixing.',
   'warning',
   (SELECT id FROM public.exercises WHERE slug = 'harmonic-camelot-1')),
  ('eq-bass-heavy', 'Bass-heavy frequency balance',
   '{"all":[{"metric":"bassPct","op":">","value":55}]}'::jsonb,
   'Bass dominates the spectrum — more than 55% of the energy is in the low end.',
   'Cut bass on the master EQ by 2–3 dB, or pick tracks with cleaner low-mid separation.',
   'warning',
   (SELECT id FROM public.exercises WHERE slug = 'eq-thirds')),
  ('eq-high-thin', 'Thin high end',
   '{"all":[{"metric":"highPct","op":"<","value":15}]}'::jsonb,
   'High-frequency content is unusually low — the mix may sound dull.',
   'Add 1–2 dB of shelf above 8 kHz or bring in a track with brighter hats/cymbals during the transition.',
   'info',
   (SELECT id FROM public.exercises WHERE slug = 'eq-thirds')),
  ('eq-mid-thin', 'Mids are recessed',
   '{"all":[{"metric":"midPct","op":"<","value":20}]}'::jsonb,
   'Mid-range energy is low — vocals and melody can disappear.',
   'Boost 200–800 Hz by 1–2 dB or layer in a melodic track.',
   'info',
   (SELECT id FROM public.exercises WHERE slug = 'eq-thirds')),
  ('dr-compressed', 'Mix is over-compressed',
   '{"all":[{"metric":"dynamicRangeDb","op":"<","value":4}]}'::jsonb,
   'Dynamic range is below 4 dB — the mix is squashed and drops have no impact.',
   'Pull the master gain down 3–6 dB and turn limiting off during recording. Loudness is added at mastering, not in the mix.',
   'warning',
   (SELECT id FROM public.exercises WHERE slug = 'headroom-6db')),
  ('dr-flat', 'Low dynamic range',
   '{"all":[{"metric":"dynamicRangeDb","op":"<","value":7},{"metric":"dynamicRangeDb","op":">=","value":4}]}'::jsonb,
   'Dynamic range is on the low side.',
   'Build a clearer contrast between intro/breakdown and drops.',
   'info',
   (SELECT id FROM public.exercises WHERE slug = 'dynamic-build')),
  ('loudness-clipping', 'Loudness near clipping',
   '{"all":[{"metric":"loudnessDbfs","op":">","value":-2}]}'::jsonb,
   'Peak loudness is within 2 dB of clipping — distortion is likely.',
   'Reduce master gain by 3–6 dB and re-record.',
   'critical',
   (SELECT id FROM public.exercises WHERE slug = 'headroom-6db')),
  ('loudness-quiet', 'Mix is very quiet',
   '{"all":[{"metric":"loudnessDbfs","op":"<","value":-18}]}'::jsonb,
   'Output is unusually quiet — average peaks below -18 dBFS.',
   'Raise master gain or check that no gain stage is muted.',
   'info',
   NULL),
  ('flow-good', 'Good dynamic flow',
   '{"all":[{"metric":"dynamicRangeDb","op":">=","value":10},{"metric":"bassStability","op":">=","value":70}]}'::jsonb,
   'Energy contrast is healthy and bass stays consistent — drops have room to breathe.',
   'Push the creativity side: try a long blend or filter-only transition next.',
   'info',
   (SELECT id FROM public.exercises WHERE slug = 'long-blend-32')),
  ('beatmatch-clean', 'Tight beat grid',
   '{"all":[{"metric":"bpmConfidence","op":">=","value":0.9},{"metric":"bassStability","op":">=","value":75}]}'::jsonb,
   'Tempo and bass are both locked — the fundamentals are solid.',
   'Move on to phrasing: align every transition to a 16-bar boundary.',
   'info',
   (SELECT id FROM public.exercises WHERE slug = 'phrase-16bar'))
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  condition = EXCLUDED.condition,
  diagnosis = EXCLUDED.diagnosis,
  fix = EXCLUDED.fix,
  severity = EXCLUDED.severity,
  exercise_id = EXCLUDED.exercise_id;
