/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as EngineTestRouteImport } from './routes/engine-test'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUploadRouteImport } from './routes/app.upload'
import { Route as AppTrainingRouteImport } from './routes/app.training'
import { Route as AppStreakRouteImport } from './routes/app.streak'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProgressRouteImport } from './routes/app.progress'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPremiumRouteImport } from './routes/app.premium'
import { Route as AppMonthlyRouteImport } from './routes/app.monthly'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppDnaRouteImport } from './routes/app.dna'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCommunityRouteImport } from './routes/app.community'
import { Route as AppCoachRouteImport } from './routes/app.coach'
import { Route as AppCareerRouteImport } from './routes/app.career'
import { Route as AppAnalysesRouteImport } from './routes/app.analyses'
import { Route as AppAchievementsRouteImport } from './routes/app.achievements'
import { Route as AppProcessingJobIdRouteImport } from './routes/app.processing.$jobId'
import { Route as AppAnalysesIdRouteImport } from './routes/app.analyses.$id'
import { Route as AnalysisProcessingJobIdRouteImport } from './routes/analysis.processing.$jobId'
import { Route as AppAnalysesIdCompareRouteImport } from './routes/app.analyses.$id.compare'
import { Route as AppAnalysesIdTransitionsTIdxRouteImport } from './routes/app.analyses.$id.transitions.$tIdx'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineTestRoute = EngineTestRouteImport.update({
  id: '/engine-test',
  path: '/engine-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingRoute = AppTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppRoute,
} as any)
const AppStreakRoute = AppStreakRouteImport.update({
  id: '/streak',
  path: '/streak',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPremiumRoute = AppPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AppRoute,
} as any)
const AppMonthlyRoute = AppMonthlyRouteImport.update({
  id: '/monthly',
  path: '/monthly',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppDnaRoute = AppDnaRouteImport.update({
  id: '/dna',
  path: '/dna',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppCareerRoute = AppCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalysesRoute = AppAnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessingJobIdRoute = AppProcessingJobIdRouteImport.update({
  id: '/processing/$jobId',
  path: '/processing/$jobId',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalysesIdRoute = AppAnalysesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAnalysesRoute,
} as any)
const AnalysisProcessingJobIdRoute = AnalysisProcessingJobIdRouteImport.update({
  id: '/analysis/processing/$jobId',
  path: '/analysis/processing/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalysesIdCompareRoute = AppAnalysesIdCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppAnalysesIdRoute,
} as any)
const AppAnalysesIdTransitionsTIdxRoute =
  AppAnalysesIdTransitionsTIdxRouteImport.update({
    id: '/transitions/$tIdx',
    path: '/transitions/$tIdx',
    getParentRoute: () => AppAnalysesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/engine-test': typeof EngineTestRoute
  '/pricing': typeof PricingRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/analyses': typeof AppAnalysesRouteWithChildren
  '/app/career': typeof AppCareerRoute
  '/app/coach': typeof AppCoachRoute
  '/app/community': typeof AppCommunityRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dna': typeof AppDnaRoute
  '/app/library': typeof AppLibraryRoute
  '/app/monthly': typeof AppMonthlyRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/streak': typeof AppStreakRoute
  '/app/training': typeof AppTrainingRoute
  '/app/upload': typeof AppUploadRoute
  '/app/': typeof AppIndexRoute
  '/analysis/processing/$jobId': typeof AnalysisProcessingJobIdRoute
  '/app/analyses/$id': typeof AppAnalysesIdRouteWithChildren
  '/app/processing/$jobId': typeof AppProcessingJobIdRoute
  '/app/analyses/$id/compare': typeof AppAnalysesIdCompareRoute
  '/app/analyses/$id/transitions/$tIdx': typeof AppAnalysesIdTransitionsTIdxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/engine-test': typeof EngineTestRoute
  '/pricing': typeof PricingRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/analyses': typeof AppAnalysesRouteWithChildren
  '/app/career': typeof AppCareerRoute
  '/app/coach': typeof AppCoachRoute
  '/app/community': typeof AppCommunityRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dna': typeof AppDnaRoute
  '/app/library': typeof AppLibraryRoute
  '/app/monthly': typeof AppMonthlyRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/streak': typeof AppStreakRoute
  '/app/training': typeof AppTrainingRoute
  '/app/upload': typeof AppUploadRoute
  '/app': typeof AppIndexRoute
  '/analysis/processing/$jobId': typeof AnalysisProcessingJobIdRoute
  '/app/analyses/$id': typeof AppAnalysesIdRouteWithChildren
  '/app/processing/$jobId': typeof AppProcessingJobIdRoute
  '/app/analyses/$id/compare': typeof AppAnalysesIdCompareRoute
  '/app/analyses/$id/transitions/$tIdx': typeof AppAnalysesIdTransitionsTIdxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/engine-test': typeof EngineTestRoute
  '/pricing': typeof PricingRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/analyses': typeof AppAnalysesRouteWithChildren
  '/app/career': typeof AppCareerRoute
  '/app/coach': typeof AppCoachRoute
  '/app/community': typeof AppCommunityRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dna': typeof AppDnaRoute
  '/app/library': typeof AppLibraryRoute
  '/app/monthly': typeof AppMonthlyRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/streak': typeof AppStreakRoute
  '/app/training': typeof AppTrainingRoute
  '/app/upload': typeof AppUploadRoute
  '/app/': typeof AppIndexRoute
  '/analysis/processing/$jobId': typeof AnalysisProcessingJobIdRoute
  '/app/analyses/$id': typeof AppAnalysesIdRouteWithChildren
  '/app/processing/$jobId': typeof AppProcessingJobIdRoute
  '/app/analyses/$id/compare': typeof AppAnalysesIdCompareRoute
  '/app/analyses/$id/transitions/$tIdx': typeof AppAnalysesIdTransitionsTIdxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/engine-test'
    | '/pricing'
    | '/app/achievements'
    | '/app/analyses'
    | '/app/career'
    | '/app/coach'
    | '/app/community'
    | '/app/dashboard'
    | '/app/dna'
    | '/app/library'
    | '/app/monthly'
    | '/app/premium'
    | '/app/profile'
    | '/app/progress'
    | '/app/settings'
    | '/app/streak'
    | '/app/training'
    | '/app/upload'
    | '/app/'
    | '/analysis/processing/$jobId'
    | '/app/analyses/$id'
    | '/app/processing/$jobId'
    | '/app/analyses/$id/compare'
    | '/app/analyses/$id/transitions/$tIdx'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/engine-test'
    | '/pricing'
    | '/app/achievements'
    | '/app/analyses'
    | '/app/career'
    | '/app/coach'
    | '/app/community'
    | '/app/dashboard'
    | '/app/dna'
    | '/app/library'
    | '/app/monthly'
    | '/app/premium'
    | '/app/profile'
    | '/app/progress'
    | '/app/settings'
    | '/app/streak'
    | '/app/training'
    | '/app/upload'
    | '/app'
    | '/analysis/processing/$jobId'
    | '/app/analyses/$id'
    | '/app/processing/$jobId'
    | '/app/analyses/$id/compare'
    | '/app/analyses/$id/transitions/$tIdx'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/engine-test'
    | '/pricing'
    | '/app/achievements'
    | '/app/analyses'
    | '/app/career'
    | '/app/coach'
    | '/app/community'
    | '/app/dashboard'
    | '/app/dna'
    | '/app/library'
    | '/app/monthly'
    | '/app/premium'
    | '/app/profile'
    | '/app/progress'
    | '/app/settings'
    | '/app/streak'
    | '/app/training'
    | '/app/upload'
    | '/app/'
    | '/analysis/processing/$jobId'
    | '/app/analyses/$id'
    | '/app/processing/$jobId'
    | '/app/analyses/$id/compare'
    | '/app/analyses/$id/transitions/$tIdx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  EngineTestRoute: typeof EngineTestRoute
  PricingRoute: typeof PricingRoute
  AnalysisProcessingJobIdRoute: typeof AnalysisProcessingJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine-test': {
      id: '/engine-test'
      path: '/engine-test'
      fullPath: '/engine-test'
      preLoaderRoute: typeof EngineTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/upload': {
      id: '/app/upload'
      path: '/upload'
      fullPath: '/app/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/training': {
      id: '/app/training'
      path: '/training'
      fullPath: '/app/training'
      preLoaderRoute: typeof AppTrainingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/streak': {
      id: '/app/streak'
      path: '/streak'
      fullPath: '/app/streak'
      preLoaderRoute: typeof AppStreakRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/premium': {
      id: '/app/premium'
      path: '/premium'
      fullPath: '/app/premium'
      preLoaderRoute: typeof AppPremiumRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monthly': {
      id: '/app/monthly'
      path: '/monthly'
      fullPath: '/app/monthly'
      preLoaderRoute: typeof AppMonthlyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dna': {
      id: '/app/dna'
      path: '/dna'
      fullPath: '/app/dna'
      preLoaderRoute: typeof AppDnaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coach': {
      id: '/app/coach'
      path: '/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/career': {
      id: '/app/career'
      path: '/career'
      fullPath: '/app/career'
      preLoaderRoute: typeof AppCareerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analyses': {
      id: '/app/analyses'
      path: '/analyses'
      fullPath: '/app/analyses'
      preLoaderRoute: typeof AppAnalysesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/processing/$jobId': {
      id: '/app/processing/$jobId'
      path: '/processing/$jobId'
      fullPath: '/app/processing/$jobId'
      preLoaderRoute: typeof AppProcessingJobIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analyses/$id': {
      id: '/app/analyses/$id'
      path: '/$id'
      fullPath: '/app/analyses/$id'
      preLoaderRoute: typeof AppAnalysesIdRouteImport
      parentRoute: typeof AppAnalysesRoute
    }
    '/analysis/processing/$jobId': {
      id: '/analysis/processing/$jobId'
      path: '/analysis/processing/$jobId'
      fullPath: '/analysis/processing/$jobId'
      preLoaderRoute: typeof AnalysisProcessingJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/analyses/$id/compare': {
      id: '/app/analyses/$id/compare'
      path: '/compare'
      fullPath: '/app/analyses/$id/compare'
      preLoaderRoute: typeof AppAnalysesIdCompareRouteImport
      parentRoute: typeof AppAnalysesIdRoute
    }
    '/app/analyses/$id/transitions/$tIdx': {
      id: '/app/analyses/$id/transitions/$tIdx'
      path: '/transitions/$tIdx'
      fullPath: '/app/analyses/$id/transitions/$tIdx'
      preLoaderRoute: typeof AppAnalysesIdTransitionsTIdxRouteImport
      parentRoute: typeof AppAnalysesIdRoute
    }
  }
}

interface AppAnalysesIdRouteChildren {
  AppAnalysesIdCompareRoute: typeof AppAnalysesIdCompareRoute
  AppAnalysesIdTransitionsTIdxRoute: typeof AppAnalysesIdTransitionsTIdxRoute
}

const AppAnalysesIdRouteChildren: AppAnalysesIdRouteChildren = {
  AppAnalysesIdCompareRoute: AppAnalysesIdCompareRoute,
  AppAnalysesIdTransitionsTIdxRoute: AppAnalysesIdTransitionsTIdxRoute,
}

const AppAnalysesIdRouteWithChildren = AppAnalysesIdRoute._addFileChildren(
  AppAnalysesIdRouteChildren,
)

interface AppAnalysesRouteChildren {
  AppAnalysesIdRoute: typeof AppAnalysesIdRouteWithChildren
}

const AppAnalysesRouteChildren: AppAnalysesRouteChildren = {
  AppAnalysesIdRoute: AppAnalysesIdRouteWithChildren,
}

const AppAnalysesRouteWithChildren = AppAnalysesRoute._addFileChildren(
  AppAnalysesRouteChildren,
)

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppAnalysesRoute: typeof AppAnalysesRouteWithChildren
  AppCareerRoute: typeof AppCareerRoute
  AppCoachRoute: typeof AppCoachRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDnaRoute: typeof AppDnaRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppMonthlyRoute: typeof AppMonthlyRoute
  AppPremiumRoute: typeof AppPremiumRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStreakRoute: typeof AppStreakRoute
  AppTrainingRoute: typeof AppTrainingRoute
  AppUploadRoute: typeof AppUploadRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProcessingJobIdRoute: typeof AppProcessingJobIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppAnalysesRoute: AppAnalysesRouteWithChildren,
  AppCareerRoute: AppCareerRoute,
  AppCoachRoute: AppCoachRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDnaRoute: AppDnaRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppMonthlyRoute: AppMonthlyRoute,
  AppPremiumRoute: AppPremiumRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStreakRoute: AppStreakRoute,
  AppTrainingRoute: AppTrainingRoute,
  AppUploadRoute: AppUploadRoute,
  AppIndexRoute: AppIndexRoute,
  AppProcessingJobIdRoute: AppProcessingJobIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  EngineTestRoute: EngineTestRoute,
  PricingRoute: PricingRoute,
  AnalysisProcessingJobIdRoute: AnalysisProcessingJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
